---
# Needed for add-apt-repository
- name: Install python-software-properties
  apt: pkg=python-software-properties state=installed update-cache=yes
  tags:
    - apt

- name: Add repository key
  apt_key: data="{{ lookup('file', 'ACCC4CF8.asc') }}"  state=present
  tags:
    - apt

- name: Add PostgreSQL repository
  apt_repository: repo='${postgresql.repo}' state=present
  tags:
    - apt
